name: Terraform CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive
      # continue-on-error: false

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate
